[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@thirdweb-dev/=node_modules/@thirdweb-dev/',
    '@openzeppelin/=node_modules/@openzeppelin/'
]

# Add these lines:
thirdweb_api_key = "${THIRDWEB_API_KEY}"
rpc_url = "https://656476.rpc.thirdweb.com/${THIRDWEB_API_KEY}"
via_ir = true       # Enable the IR-based compiler pipeline
optimizer = true    # Enable the optimizer
optimizer_runs = 200

private_key = "${PRIVATE_KEY}"
admin_private_key = "${ADMIN_PRIVATE_KEY}"
organization_address = "${ORGANIZATION_ADMIN}"




# See more config options https://github.com/foundry-rs/foundry/tree/master/config